template-conf: remove image-mklibs
support was removed upstream so it needs to be removed here as well,
otherwise we parsing errors like
ERROR: ParseError in configuration INHERITs: image-mklibs.bbclass

Closes #134

Signed-off-by: Konrad Weihmann <kweihmann@outlook.com>